
general {
    hide_cursor = true
}

background {
    monitor =
    path = /home/harlik/Assets/Walls/5.jpg

    blur_passes = 1
    blur_size = 4
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

label {
    monitor = DP-2
    text = $TIME12
    color = rgba(220, 220, 230, 0.9)
    shadow_passes = 2
    shadow_size = 1
    font_size = 26
    font_family = FiraCode Bold

    position = 0, 330
    valign = center
    halign = center
}
label {
    monitor = DP-2
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = rgba(220, 220, 230, 0.9)
    shadow_passes = 2
    shadow_size = 1
    font_size = 16
    font_family = FiraCode SemiBold

    position = 0, 285
    valign = center
    halign = center
}
label {
    monitor = DP-2
    text = Welcome back, $USER
    color = rgba(220, 220, 230, 0.6)
    shadow_passes = 2
    shadow_size = 1
    font_size = 18
    font_family = FiraCode Bold

    position = 0, -5
    valign = center
    halign = center
}

image {
    monitor = DP-2
    path = /home/harlik/Assets/Avatars/musashi.jpg
    size = 100
    border_size = 1

    position = 0, 80
    valign = center
    halign = center
}

input-field {
    monitor = DP-2

    size = 250, 60
    outline_thickness = 1
    rounding = -1

    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    dots_rounding = -1

    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.2)
    check_color = rgba(204, 136, 34, 0.8)
    fail_color = rgba(204, 34, 34, 0.8)
    font_color = rgba(220, 220, 230, 0.8)

    placeholder_text = 
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>

    hide_input = false
    fade_on_empty = false
    fade_timeout = 1000
    fail_transition = 300
    
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false

    position = 0, -65
    halign = center
    valign = center
}

label {
    monitor = DP-2
    text = $LAYOUT[!, ru]
    color = rgba(200, 200, 200, 1.0)
    font_family = FiraCode Bold
    font_size = 16
    position = 0, -125
    halign = center
    valign = center
}

