# wallpaper {
# 	monitor = HDMI-A-1
# 	path = /home/harlik/Assets/Walls/4.jpg
# 	fit_mode = cover
# }
# wallpaper {
# 	monitor = DP-2
# 	path = /home/harlik/Assets/Walls/4.jpg
# 	fit_mode = cover
# }

splash = false
ipc = on
