
#      _______  ________  ________  ________  ________ 
#    ╱╱       ╲╱    ╱   ╲╱        ╲╱        ╲╱        ╲
#   ╱╱        ╱         ╱    ╱    ╱    ╱    ╱         ╱
#  ╱       --╱         ╱         ╱        _╱   ╱  ╱  ╱ 
#  ╲________╱╲___╱____╱╲___╱____╱╲____╱___╱╲__╱__╱__╱  

# One of the lucky charm.

source = ./modules/keybinds.conf # Keybinds
source = ./modules/looknfeel.conf # Visuals
source = ./modules/animations.conf # Animations
source = ./modules/monitors.conf # Monitors
source = ./modules/inputs.conf # Input
source = ./modules/windowrules.conf # Window & workspace rules


## Autostart

exec-once = hyprlock
exec-once = wal -R && wpg -s $(wpg -c) && hyprpaper
exec-once = ~/Scripts/restore-wall.sh
exec-once = mako
exec-once = waybar
exec-once = hyprctl setcursor "Qogir-Light" 20

## Env vars
# (https://wiki.hypr.land/Configuring/Environment-variables/)

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24


## Permissions (Restart neede) 
# (https://wiki.hypr.land/Configuring/Permissions/)

