
## Input module
# (https://wiki.hypr.land/Configuring/Variables/#input)

input {
    kb_layout = us, ru
    kb_options = caps:none, grp:win_space_toggle
    repeat_delay = 400
    repeat_rate = 55
    follow_mouse = 1
    force_no_accel = 0
    accel_profile = flat

    touchpad {
        natural_scroll = true
    }
}

## Gestures
# (https://wiki.hypr.land/Configuring/Gestures)

gesture = 3, horizontal, workspace


## Devices
# (https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs)

device {
    name = logitech-pro-x-1
    sensitivity = -0.6
    accel_profile = flat
}

device {
    name = apple-inc.-magic-trackpad
    scroll_factor = 0.8
}