
## Window & workspace rules
# (https://wiki.hypr.land/Configuring/Window-Rules/)
# (https://wiki.hypr.land/Configuring/Workspace-Rules/)

windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}


# Window rules

# Picture-in-Picture
windowrule {
    name = hyde_picture_in_picture
    match:title = ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
    tag = +picture-in-picture
    tag = +hyde_picture_in_picture
    float = true
    keep_aspect_ratio = true
    move = (monitor_w*0.01) (monitor_h*0.63)
    size = (monitor_w*0.35) (monitor_h*0.35)
    pin = true
    no_blur = on
    opaque = on
}

# Floating
windowrule = match:title ^(Open File)(.*)$, center on
windowrule = match:title ^(Open File)(.*)$, float on
windowrule = match:title ^(Select a File)(.*)$, center on
windowrule = match:title ^(Select a File)(.*)$, float on
windowrule = match:title ^(Open Folder)(.*)$, center on
windowrule = match:title ^(Open Folder)(.*)$, float on
windowrule = match:title ^(Save As)(.*)$, center on
windowrule = match:title ^(Save As)(.*)$, float on
windowrule = match:title ^(Library)(.*)$, center on
windowrule = match:title ^(Library)(.*)$, float on
windowrule = match:title ^(File Upload)(.*)$, center on
windowrule = match:title ^(File Upload)(.*)$, float on
windowrule = match:title ^(.*)(wants to save)$, center on
windowrule = match:title ^(.*)(wants to save)$, float on
windowrule = match:class ^(pavucontrol)$, float on
windowrule = match:class ^(pavucontrol)$, size (monitor_w*.45) (monitor_h*.45)
windowrule = match:class ^(pavucontrol)$, center on
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, float on
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, size (monitor_w*.45) (monitor_h*.45)
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, center on
windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(blueman-manager)$, size (monitor_w*.45) (monitor_h*.45)
windowrule = match:class ^(blueman-manager)$, center on
windowrule = match:class ^(thunar)$, float on
windowrule = match:class ^(thunar)$, size (monitor_w*.45) (monitor_h*.45)
windowrule = match:class ^(thunar)$, center on

# Tearing
windowrule = match:title .*\.exe, immediate on
windowrule = match:title .*minecraft.*, immediate on
windowrule = match:class ^(steam_app).*, immediate on

# Jetbrain IDEs
windowrule = match:class ^jetbrains-.*$, match:float 1, match:title ^$|^\s$|^win\d+$, no_initial_focus on
windowrule = match:class ^jetbrains-.*$, no_blur on
windowrule = match:class ^jetbrains-.*$, opaque on

# Discord
windowrule = match:class vesktop, no_blur on
windowrule = match:class vesktop, opaque on

# Lunar Client
windowrule = fullscreen on, match:class ^Lunar Client.*$


# Layer rules

layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0.1, match:namespace rofi


# Workspace rules

workspace = 1, monitor:DP-2, persistent:true
workspace = 2, monitor:DP-2, persistent:true
workspace = 3, monitor:DP-2, persistent:true
workspace = 4, monitor:DP-2, persistent:true
workspace = 5, monitor:DP-2, persistent:true
workspace = 6, monitor:HDMI-A-1, persistent:true
workspace = 7, monitor:HDMI-A-1, persistent:true
workspace = 8, monitor:HDMI-A-1, persistent:true


## Dwindle
# (https://wiki.hypr.land/Configuring/Dwindle-Layout/)

dwindle {
    pseudotile = true
    preserve_split = true 
}


## Master layout
# (https://wiki.hypr.land/Configuring/Master-Layout/)

master {
    new_status = master
}


## Misc
# (https://wiki.hypr.land/Configuring/Variables/#misc)

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}